export const BANKS = [
  { value: 'VNPAYQR', text: 'Ngân hàng VNPAYQR' },
  { value: 'NCB', text: 'Ngân hàng NCB' },
  { value: 'SCB', text: 'Ngân hàng SCB' },
  { value: 'SACOMBANK', text: 'Ngân hàng SACOMBANK' },
  { value: 'EXIMBANK', text: 'Ngân hàng EXIMBANK' },
  { value: 'MSBANK', text: 'Ngân hàng MSBANK' },
  { value: 'NAMABANK', text: 'Ngân hàng NAMABANK' },
  { value: 'VISA', text: 'Ngân hàng VISA' },
  { value: 'VNMART', text: 'Ngân hàng VNMART' },
  { value: 'VIETINBANK', text: 'Ngân hàng VIETINBANK' },
  { value: 'VIETCOMBANK', text: 'Ngân hàng VIETCOMBANK' },
  { value: 'HDBANK', text: 'Ngân hàng HDBANK' },
  { value: 'DONGABANK', text: 'Ngân hàng Dong A' },
  { value: 'TPBANK', text: 'Ngân hàng Tp Bank' },
  { value: 'OJB', text: 'Ngân hàng OceanBank' },
  { value: 'BIDV', text: 'Ngân hàng BIDV' },
  { value: 'TECHCOMBANK', text: 'Ngân hàng Techcombank' },
  { value: 'VPBANK', text: 'Ngân hàng VPBank' },
  { value: 'AGRIBANK', text: 'Ngân hàng AGRIBANK' },
  { value: 'MBBANK', text: 'Ngân hàng MBBank' },
  { value: 'ACB', text: 'Ngân hàng ACB' },
  { value: 'OCB', text: 'Ngân hàng OCB' },
  { value: 'SHB', text: 'Ngân hàng SHB' },
  { value: 'IVB', text: 'Ngân hàng IVB' },
];
